name: Flutter Unit Tests

on:
  push:
    branches:
      - feat/product

jobs:
  Flutter_Tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '21.x'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Run Specific Unit Tests
        run: |
          set -e  # Para parar caso algum teste falhe
          flutter test test/src/domain/repositories/products/product_repository_unit_test.dart
          flutter test test/src/domain/repositories/stores/store_repository_unit_test.dart
          flutter test test/src/domain/repositories/users/user_repository_unit_test.dart
